services:
  api:
    image: mmilanta/special-bernacle-debug:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env 
    volumes:
      - ./src:/src
  git-store:
    # Image is only used locally, to avoid building all services individually
    image: mmilanta/git-store:latest
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 5000 --reload"
    ports:
      - "5000:5000"
    env_file:
      - .env