services:
  api:
    image: ghcr.io/mmilanta/special-barnacle:main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment:
      - GIT_STORE_HOST=git-store
      - GIT_STORE_PORT=5000
    
    env_file:
      - .env
    volumes:
      - ./src:/src
