services:
  api:
    image: ghcr.io/mmilanta/special-barnacle:main
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - "8080:8080"
    environment:
      - GIT_STORE_HOST=git-store
      - GIT_STORE_PORT=5000
    
    env_file:
      - .env
    volumes:
      - ./src:/src
