services:
  api:
    image: ghcr.io/mmilanta/special-barnacle:main
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "80:8000"
    env_file:
      - .env
  git-store:
    # Image is only used locally, to avoid building all services individually
    image: ghcr.io/mmilanta/git-store:main
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 5000 --reload"
    ports:
      - "5000:5000"
    env_file:
      - .env-git-store
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
