version: '3.8'

services:
  reverse-proxy:
    image: traefik:v3.2
    command:
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.le.acme.email=your-email@example.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    environment:
      - TRAEFIK_LOG_LEVEL=INFO

  api:
    image: ghcr.io/mmilanta/special-barnacle:main
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`www.ricette-nonna-aua.it`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=le"
      - "traefik.http.services.api.loadbalancer.server.port=8000"

  git-store:
    image: ghcr.io/mmilanta/git-store:main
    command: >
      sh -c "uvicorn app:app --host 0.0.0.0 --port 5000"
    env_file:
      - .env-git-store
    expose:
      - "5000"  # Only expose internally to the Docker network (not to the host)

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30